package com.example.util

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    URDU("ur", "اردو")
}

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        val strings = if (lang == AppLanguage.URDU) urduStrings else englishStrings
        return strings[key] ?: englishStrings[key] ?: key
    }

    private val englishStrings = mapOf(
        // App
        "app_title" to "Shop Manager",
        "switch_shop" to "Switch Shop",
        "add_shop" to "Add New Shop",
        "shop_name" to "Shop Name",
        "business_type" to "Business Type",
        "currency" to "Currency",
        "phone" to "Phone Number",
        "address" to "Address",
        "active_shop" to "Active Shop",
        "role_owner" to "Owner",
        "role_manager" to "Manager",
        "role_cashier" to "Cashier",
        "switch_staff" to "Switch User",
        "lock_terminal" to "Lock Terminal",
        "enter_pin" to "Enter 4-Digit PIN",
        "pin_incorrect" to "Incorrect PIN",
        "permission_denied" to "Access Denied: Owner/Manager permission required",

        // Navigation
        "tab_pos" to "Billing",
        "tab_inventory" to "Inventory",
        "tab_customers" to "Udhaar / Customers",
        "tab_suppliers" to "Suppliers",
        "tab_zakat" to "Zakat Tracker",
        "tab_staff" to "Staff & Payroll",
        "tab_expenses" to "Expenses",
        "tab_reports" to "Reports",

        // POS
        "quick_billing" to "Point of Sale (POS)",
        "search_items" to "Search items or scan barcode...",
        "all_categories" to "All",
        "cart" to "Cart",
        "cart_empty" to "Cart is empty. Tap items to add.",
        "customer" to "Customer",
        "walk_in" to "Cash Walk-In",
        "select_customer" to "Select Customer",
        "item_discount" to "Item Discount",
        "bill_discount" to "Bill Discount",
        "subtotal" to "Subtotal",
        "discount" to "Discount",
        "grand_total" to "Total Amount",
        "payment_method" to "Payment Type",
        "pay_cash" to "Full Cash",
        "pay_credit" to "Full Udhaar (Credit)",
        "pay_partial" to "Partial (Cash + Udhaar)",
        "amount_received" to "Amount Received",
        "remaining_udhaar" to "Added to Udhaar",
        "complete_sale" to "Complete Sale & Receipt",
        "clear_cart" to "Clear Cart",
        "receipt" to "Sale Receipt",
        "share_whatsapp" to "Send on WhatsApp",
        "share_receipt" to "Share Receipt",
        "print_receipt" to "Print / Save Receipt",

        // Inventory
        "items_count" to "Items",
        "add_item" to "Add New Item",
        "edit_item" to "Edit Item",
        "delete_item" to "Delete Item",
        "item_name" to "Item Name",
        "item_name_urdu" to "Item Name (Urdu)",
        "category" to "Category",
        "unit" to "Unit",
        "purchase_price" to "Purchase / Cost Price",
        "sale_price" to "Sale Price",
        "stock_qty" to "Quantity in Stock",
        "low_stock_threshold" to "Low Stock Alert At",
        "barcode" to "Barcode / QR",
        "is_service" to "Labor / Service Item (No stock count)",
        "low_stock_warning" to "Low Stock Alert",
        "profit_margin" to "Profit Margin",
        "stock_value_cost" to "Total Inventory Value (Cost)",
        "scan_barcode" to "Scan / Enter Barcode",

        // Zakat
        "zakat_tracker_title" to "Zakat Wealth & Nisab Tracker",
        "zakat_subtitle" to "Real-time calculation of trading assets, cash, receivables & nisab status",
        "sahib_e_nisab" to "Sahib-e-Nisab (Eligible for Zakat)",
        "below_nisab" to "Below Nisab Threshold",
        "nisab_threshold" to "Nisab Threshold",
        "edit_nisab" to "Configure Nisab",
        "net_zakatable_wealth" to "Net Zakatable Wealth",
        "zakat_due_calculated" to "Zakat Due (2.5%)",
        "hawl_status" to "Hawl (Lunar Year Cycle)",
        "days_elapsed" to "Days Elapsed",
        "days_remaining" to "Days Remaining",
        "asset_inventory" to "Inventory Value (Cost)",
        "asset_cash" to "Cash in Hand",
        "asset_receivables" to "Udhaar Receivables",
        "liability_payables" to "Supplier Payables",
        "record_zakat_payment" to "Record Zakat Paid",
        "zakat_guide" to "Zakat Rules Guide",
        "zakat_guide_text" to "Zakat is obligatory (Fard) at 2.5% on commercial stock valued at cost, liquid cash, and reliable receivables, minus immediate liabilities, provided wealth remains above Nisab for one lunar year (354 days).",

        // Customers & Udhaar
        "customers_title" to "Customer Credit (Udhaar) Ledger",
        "add_customer" to "Add Customer",
        "search_customers" to "Search customer name or phone...",
        "current_due" to "Current Outstanding Due",
        "total_purchases" to "Total Purchases",
        "total_paid" to "Total Paid",
        "record_payment" to "Record Payment",
        "add_manual_due" to "Give Credit (New Due)",
        "ledger_history" to "Ledger History",
        "old_due" to "Previous Due",
        "current_purchase" to "Current Items",
        "total_due" to "Total Due",
        "send_reminder_whatsapp" to "WhatsApp Due Reminder",
        "send_reminder_sms" to "SMS Due Reminder",
        "payment_note" to "Note / Description",

        // Suppliers
        "suppliers_title" to "Supplier / Vendor Ledger",
        "add_supplier" to "Add Supplier",
        "company_name" to "Company / Brand Name",
        "payable_balance" to "Balance Owed to Supplier",
        "record_supplier_payment" to "Record Payment to Supplier",
        "record_supplier_purchase" to "Record Stock Purchase on Credit",

        // Staff & Payroll
        "staff_title" to "Staff & Employee Payroll",
        "add_staff" to "Add Staff Member",
        "mark_attendance" to "Mark Today's Attendance",
        "status_present" to "Present",
        "status_absent" to "Absent",
        "status_half_day" to "Half Day",
        "status_leave" to "Leave",
        "monthly_salary" to "Monthly Salary",
        "daily_wage" to "Daily Wage",
        "earned_salary" to "Salary Earned (Attendance-based)",
        "salary_paid" to "Salary Paid",
        "salary_balance" to "Salary Owed",
        "pay_salary" to "Pay Salary",
        "activity_log" to "Audit & Activity Log",

        // Expenses
        "expenses_title" to "Shop Expenses",
        "add_expense" to "Add Expense",
        "expense_category" to "Expense Category",
        "expense_amount" to "Expense Amount",
        "expense_rent" to "Shop Rent",
        "expense_electricity" to "Electricity & Utilities",
        "expense_transport" to "Transportation & Cargo",
        "expense_refreshment" to "Tea & Refreshments",
        "expense_maintenance" to "Repairs & Maintenance",
        "expense_misc" to "Miscellaneous",

        // Reports
        "reports_title" to "Financial Reports & Analytics",
        "gross_sales" to "Gross Sales",
        "cogs" to "Cost of Goods Sold (COGS)",
        "gross_profit" to "Gross Profit",
        "total_expenses" to "Total Expenses",
        "net_profit" to "Net Profit",
        "udhaar_given" to "Udhaar Given",
        "udhaar_collected" to "Udhaar Collected",
        "backup_restore" to "Backup & Data Export",
        "export_csv" to "Export Data (CSV / Excel)",
        "export_json" to "Export Backup File (JSON)",
        "import_json" to "Restore Backup",

        // Universal Calculator
        "calculator" to "Universal Calculator",
        "insert_value" to "Insert Value",
        "clear" to "C",

        // Common
        "save" to "Save",
        "cancel" to "Cancel",
        "close" to "Close",
        "delete" to "Delete",
        "edit" to "Edit",
        "confirm" to "Confirm",
        "date" to "Date",
        "time" to "Time",
        "notes" to "Notes",
        "success" to "Success",
        "rs" to "Rs."
    )

    private val urduStrings = mapOf(
        // App
        "app_title" to "شاپ مینیجر",
        "switch_shop" to "دکان تبدیل کریں",
        "add_shop" to "نئی دکان شامل کریں",
        "shop_name" to "دکان کا نام",
        "business_type" to "کاروبار کی قسم",
        "currency" to "کرنسی",
        "phone" to "فون نمبر",
        "address" to "پتہ",
        "active_shop" to "موجودہ دکان",
        "role_owner" to "مالک",
        "role_manager" to "مینیجر",
        "role_cashier" to "کیشیئر / سیلز مین",
        "switch_staff" to "صارف تبدیل کریں",
        "lock_terminal" to "ٹرمینل لاک کریں",
        "enter_pin" to "4 ہندسوں کا پن کوڈ درج کریں",
        "pin_incorrect" to "غلط پن کوڈ",
        "permission_denied" to "اجازت نہیں: مالک یا مینیجر کی منظوری درکار ہے",

        // Navigation
        "tab_pos" to "فروخت / بلنگ",
        "tab_inventory" to "اسٹاک / سامان",
        "tab_customers" to "گاہک کھاتہ / ادھار",
        "tab_suppliers" to "سپلائر کھاتہ",
        "tab_zakat" to "زکوٰۃ ٹریکر",
        "tab_staff" to "ملازمین و تنخواہ",
        "tab_expenses" to "اخراجات",
        "tab_reports" to "رپورٹ و منافع",

        // POS
        "quick_billing" to "فروخت و رسید (POS)",
        "search_items" to "سامان تلاش کریں یا بارکوڈ اسکین کریں...",
        "all_categories" to "تمام",
        "cart" to "بل فہرست",
        "cart_empty" to "بل خالی ہے۔ سامان منتخب کریں۔",
        "customer" to "گاہک",
        "walk_in" to "عام گاہک (نقد)",
        "select_customer" to "گاہک منتخب کریں",
        "item_discount" to "سامان پر رعایت",
        "bill_discount" to "بل پر کل رعایت",
        "subtotal" to "میزان بل",
        "discount" to "رعایت",
        "grand_total" to "کل رقم",
        "payment_method" to "ادائیگی کی قسم",
        "pay_cash" to "مکمل نقد",
        "pay_credit" to "مکمل ادھار",
        "pay_partial" to "کچھ نقد + باقی ادھار",
        "amount_received" to "موصول شدہ رقم",
        "remaining_udhaar" to "ادھار میں شامل رقم",
        "complete_sale" to "فروخت مکمل کریں اور رسید بنائیں",
        "clear_cart" to "بل صاف کریں",
        "receipt" to "فروخت کی رسید",
        "share_whatsapp" to "واٹس ایپ پر بھیجیں",
        "share_receipt" to "رسید شیئر کریں",
        "print_receipt" to "رسید محفوظ کریں / پرنٹ",

        // Inventory
        "items_count" to "اشیاء",
        "add_item" to "نیا سامان شامل کریں",
        "edit_item" to "سامان میں ترمیم کریں",
        "delete_item" to "سامان حذف کریں",
        "item_name" to "سامان کا نام (انگریزی)",
        "item_name_urdu" to "سامان کا نام (اردو)",
        "category" to "کیٹیگری",
        "unit" to "اکائی / پیمانہ",
        "purchase_price" to "قیمت خرید (لاگت)",
        "sale_price" to "قیمت فروخت",
        "stock_qty" to "موجودہ تعداد / اسٹاک",
        "low_stock_threshold" to "کم اسٹاک الرٹ کی حد",
        "barcode" to "بارکوڈ / QR",
        "is_service" to "خدمت / مزدوری (بغیر اسٹاک)",
        "low_stock_warning" to "کم اسٹاک کا انتباہ",
        "profit_margin" to "منافع",
        "stock_value_cost" to "کل مالیت مال تجارت (لاگت)",
        "scan_barcode" to "بارکوڈ اسکین کریں یا درج کریں",

        // Zakat
        "zakat_tracker_title" to "زکوٰۃ مال تجارت و نصاب ٹریکر",
        "zakat_subtitle" to "مالِ تجارت، نقدی اور قابلِ وصول ادھار کا خودکار زکوٰۃ حساب",
        "sahib_e_nisab" to "صاحبِ نصاب (زکوٰۃ واجب کی حد)",
        "below_nisab" to "نصاب سے کم مالیت",
        "nisab_threshold" to "نصاب کی حد",
        "edit_nisab" to "نصاب کی رقم تبدیل کریں",
        "net_zakatable_wealth" to "خالص قابلِ زکوٰۃ مالیت",
        "zakat_due_calculated" to "واجب الادا زکوٰۃ (2.5٪)",
        "hawl_status" to "حول (قمری سال کا چکر)",
        "days_elapsed" to "گزشتہ ایام",
        "days_remaining" to "باقی ایام",
        "asset_inventory" to "مال تجارت کی مالیت (خریداری قیمت)",
        "asset_cash" to "موجودہ نقدی (کیش)",
        "asset_receivables" to "گاہکوں کے واجبات (ادھار)",
        "liability_payables" to "سپلائر کو واجب الادا رقم",
        "record_zakat_payment" to "زکوٰۃ کی ادائیگی درج کریں",
        "zakat_guide" to "زکوٰۃ کے شرعی اصول",
        "zakat_guide_text" to "دکان کے مال تجارت کی مالیت (قیمت خرید)، دستیاب کیش اور وصول طلب ادھار پر سال گزرنے کے بعد 2.5 فیصد (چالیسواں حصہ) زکوٰۃ فرض ہے۔ فوری واجب الادا قرضے منفی کیے جاتے ہیں۔",

        // Customers & Udhaar
        "customers_title" to "گاہک کھاتہ و ادھار کا انتظام",
        "add_customer" to "نیا گاہک شامل کریں",
        "search_customers" to "گاہک کا نام یا فون تلاش کریں...",
        "current_due" to "موجودہ بقایا ادھار",
        "total_purchases" to "کل خریداری",
        "total_paid" to "کل وصول شدہ",
        "record_payment" to "رقم وصول کریں",
        "add_manual_due" to "نیا ادھار دیں",
        "ledger_history" to "کھاتہ تفصیل",
        "old_due" to "سابقہ بقایا",
        "current_purchase" to "موجودہ خریداری",
        "total_due" to "کل واجب الادا رقم",
        "send_reminder_whatsapp" to "واٹس ایپ پر بقایا یاد دہانی",
        "send_reminder_sms" to "ایس ایم ایس یاد دہانی",
        "payment_note" to "تفصیل / نوٹ",

        // Suppliers
        "suppliers_title" to "سپلائر / وینڈر کھاتہ",
        "add_supplier" to "نیا سپلائر شامل کریں",
        "company_name" to "کمپنی / برانڈ",
        "payable_balance" to "سپلائر کو واجب الادا رقم",
        "record_supplier_payment" to "سپلائر کو رقم ادا کریں",
        "record_supplier_purchase" to "ادھار پر مال کی خریداری درج کریں",

        // Staff & Payroll
        "staff_title" to "ملازمین کی حاضری و تنخواہ کھاتہ",
        "add_staff" to "نیا ملازم شامل کریں",
        "mark_attendance" to "آج کی حاضری لگائیں",
        "status_present" to "حاضر",
        "status_absent" to "غیر حاضر",
        "status_half_day" to "نصف یوم",
        "status_leave" to "چھٹی",
        "monthly_salary" to "ماہانہ تنخواہ",
        "daily_wage" to "روزانہ اجرت",
        "earned_salary" to "کمائی گئی تنخواہ (حاضری کے مطابق)",
        "salary_paid" to "ادا شدہ تنخواہ",
        "salary_balance" to "باقی واجب الادا تنخواہ",
        "pay_salary" to "تنخواہ ادا کریں",
        "activity_log" to "کارکردگی و لاگ بک",

        // Expenses
        "expenses_title" to "دکان کے روزمرہ اخراجات",
        "add_expense" to "خرچہ درج کریں",
        "expense_category" to "خرچے کی مد",
        "expense_amount" to "خرچے کی رقم",
        "expense_rent" to "دکان کا کرایہ",
        "expense_electricity" to "بجلی و یوٹیلیٹیز",
        "expense_transport" to "کرایہ مال و باربرداری",
        "expense_refreshment" to "چائے و تواضع",
        "expense_maintenance" to "مرمت و دیکھ بھال",
        "expense_misc" to "متفرق اخراجات",

        // Reports
        "reports_title" to "مالی رپورٹس و تجزیہ",
        "gross_sales" to "کل فروخت",
        "cogs" to "فروخت شدہ سامان کی لاگت",
        "gross_profit" to "مجموعی منافع",
        "total_expenses" to "کل اخراجات",
        "net_profit" to "خالص منافع",
        "udhaar_given" to "دیا گیا ادھار",
        "udhaar_collected" to "وصول شدہ ادھار",
        "backup_restore" to "بیک اپ اور ڈیٹا برآمد",
        "export_csv" to "ایکسل میں محفوظ کریں (CSV)",
        "export_json" to "مکمل بیک اپ فائل (JSON)",
        "import_json" to "بیک اپ بحال کریں",

        // Universal Calculator
        "calculator" to "یونیورسل کیلکولیٹر",
        "insert_value" to "رقم درج کریں",
        "clear" to "صاف کریں",

        // Common
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ",
        "close" to "بند کریں",
        "delete" to "حذف کریں",
        "edit" to "ترمیم",
        "confirm" to "تصدیق",
        "date" to "تاریخ",
        "time" to "وقت",
        "notes" to "نوٹ",
        "success" to "کامیابی",
        "rs" to "روپے"
    )
}
